# Generated by Django 4.2.4 on 2023-08-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='pitch_image',
        ),
        migrations.CreateModel(
            name='PitchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pitch_images/')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pitch_images/')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pitch.pitch')),
            ],
        ),
    ]
