# Generated by Django 4.2.4 on 2023-08-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0002_remove_pitch_pitch_image_pitchimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='pitch_images',
            field=models.ManyToManyField(blank=True, related_name='pitches', to='pitch.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pitch.pitch'),
        ),
        migrations.DeleteModel(
            name='PitchImage',
        ),
    ]
