# Generated by Django 4.2.4 on 2023-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0003_pitch_pitch_images_alter_image_pitch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='pitch_images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitch_images',
            field=models.ImageField(blank=True, null=True, upload_to='pitch_images/'),
        ),
    ]
